### ISSUE TITLE
Error message in console when game is finish

### ISSUE THREAD

**Issue by Dryusdan** [ashmonger/lapyrinthe#1]
Hi
I found a non-blocking error. When I finish game, a message appair in console : 
```
ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
```

:)

**Comment by ashmonger** [comment]
OK, seems this is a buffer size problem with pygame.mixer.pre_init().
Changed that in https://github.com/ashmonger/lapyrinthe/commit/3fd6875110d73a67340ab32a69688123777541ce
